version: "3"
services:
  web:
    build: .
    links:
      - redis
    ports:
      - "1443:1443"
    environment:
      - REDIS_HOST=35.230.117.94
      - GCS_BUCKET=fullsend
      - SENTRY_CLIENT=https://51e23d7263e348a7a3b90a5357c61cb2@sentry.prod.mozaws.net/168
      - SENTRY_DSN=https://51e23d7263e348a7a3b90a5357c61cb2:65e23d7263e348a7a3b90a5357c61c44@sentry.prod.mozaws.net/168
  redis:
    image: redis:alpine
  selenium-firefox:
    image: b4handjr/selenium-firefox
    ports:
      - "${VNC_PORT:-5900}:5900"
    shm_size: 2g
    volumes:
      - .:/code